// Mocks generated by Mockito 5.4.4 from annotations
// in pill_line_a_i/test/features/ex_notdata/ex_notdata_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:pill_line_a_i/features/ex_notdata/data/datasources/ex_notdata_remote_data_source.dart'
    as _i3;
import 'package:pill_line_a_i/features/ex_notdata/domain/entities/ex_notdata.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeExNotData_0 extends _i1.SmartFake implements _i2.ExNotData {
  _FakeExNotData_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ExNotDataRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockExNotDataRemoteDataSource extends _i1.Mock
    implements _i3.ExNotDataRemoteDataSource {
  MockExNotDataRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.ExNotData> getExNotData() => (super.noSuchMethod(
        Invocation.method(
          #getExNotData,
          [],
        ),
        returnValue: _i4.Future<_i2.ExNotData>.value(_FakeExNotData_0(
          this,
          Invocation.method(
            #getExNotData,
            [],
          ),
        )),
      ) as _i4.Future<_i2.ExNotData>);

  @override
  _i4.Future<void> updateExNotData(_i2.ExNotData? data) => (super.noSuchMethod(
        Invocation.method(
          #updateExNotData,
          [data],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
